version: "3.9"

services:
  mysql-server:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=miriad
    ports:
      - 3306:3306
  discovery-service:
    image: miriad/discovery-service:latest
    environment:
      - DISCOVERY_HOST=discovery-service
    ports:
      - 7000:7000
  api-core:
    image: miriad/core-service:latest
    depends_on:
      - mysql-server
      - discovery-service
    environment:
      - MYSQL_HOST=mysql-server
      - DISCOVERY_HOST=discovery-service
    ports:
      - 7101-7109:7101